// build.js — bundles viewer libs via esbuild, scans folders, injects into index.html
// Build command (Cloudflare Pages): node build.js
// Local dev: npm run dev

const fs   = require('fs');
const path = require('path');
const { execSync } = require('child_process');

// ── 1. Scan slide/notebook files ──────────────────────────────────────────────
function scanDir(dir) {
  const results = [];
  if (!fs.existsSync(dir)) return results;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) results.push(...scanDir(full));
    else if (/\.(pptx?|ipynb)$/i.test(entry.name))
      results.push(full.replace(/\\/g, '/'));
  }
  return results;
}

const files = [...scanDir('slides'), ...scanDir('notebooks')];
fs.writeFileSync('data.json', JSON.stringify(files, null, 2));
console.log(`data.json: ${files.length} file(s)`);

// ── 2. Bundle browser-safe libs with esbuild ──────────────────────────────────
// notebookjs depends on jsdom (Node-only) so we keep it on CDN.
// Everything else gets bundled locally: JSZip, Chart.js, ansi_up, hljs, marked, katex.
const entry = '__bundle_entry.js';
fs.writeFileSync(entry, `
import JSZip from 'jszip';
import Chart from 'chart.js/auto';
import AnsiUp from 'ansi_up';
import hljs from 'highlight.js';
import { marked } from 'marked';
import katex from 'katex';
import renderMathInElement from 'katex/contrib/auto-render';

window.JSZip = JSZip;
window.Chart = Chart;
window.AnsiUp = AnsiUp;
window.hljs = hljs;
window.marked = marked;
window.katex = katex;
window.renderMathInElement = renderMathInElement;
`);

execSync(
  'npx esbuild __bundle_entry.js --bundle --format=iife --global-name=__libs' +
  ' --platform=browser --outfile=bundle.js --log-level=warning',
  { stdio: 'inherit' }
);
fs.unlinkSync(entry);

// pptxviewjs must load after its deps are on window — append to bundle
const pptxSrc = fs.readFileSync(
  path.join('node_modules', 'pptxviewjs', 'dist', 'PptxViewJS.min.js'), 'utf8'
);
fs.appendFileSync('bundle.js', '\n' + pptxSrc);
console.log('bundle.js written');

// ── 3. Inject into index.html ─────────────────────────────────────────────────
let html = fs.readFileSync('index.html', 'utf8');
// Remove old file injection
html = html.replace(/\n?\/\/ __INJECTED_FILES__[\s\S]*?window\.__files = \[.*?\];\n?/g, '');
const injection = `\n// __INJECTED_FILES__ (auto-generated by build.js — do not edit)\nwindow.__files = ${JSON.stringify(files)};\n`;
html = html.replace('init();', injection + 'init();');
fs.writeFileSync('index.html', html);
console.log('window.__files injected into index.html');
