// Cloudflare Pages build script — scans slides/ and notebooks/, then:
// 1. Writes data.json (for HTTP-served environments)
// 2. Injects window.__files inline into index.html (for local/file:// preview)
// Build command: node build.js
// Build output directory: / (root)

const fs = require('fs');
const path = require('path');

function scanDir(dir) {
  const results = [];
  if (!fs.existsSync(dir)) return results;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      results.push(...scanDir(full));
    } else if (/\.(pptx?|ipynb)$/i.test(entry.name)) {
      results.push(full.replace(/\\/g, '/'));
    }
  }
  return results;
}

const files = [
  ...scanDir('slides'),
  ...scanDir('notebooks'),
];

// 1. Write data.json
fs.writeFileSync('data.json', JSON.stringify(files, null, 2));
console.log(`data.json written with ${files.length} file(s):`);
files.forEach(f => console.log(' ', f));

// 2. Inject window.__files into index.html before </script>
const indexPath = 'index.html';
let html = fs.readFileSync(indexPath, 'utf8');
// Remove any previous injection
html = html.replace(/\n?\/\/ __INJECTED_FILES__[\s\S]*?window\.__files = \[.*?\];\n?/g, '');
// Inject just before init()
const injection = `\n// __INJECTED_FILES__ (auto-generated by build.js — do not edit)\nwindow.__files = ${JSON.stringify(files)};\n`;
html = html.replace('init();', injection + 'init();');
fs.writeFileSync(indexPath, html);
console.log('window.__files injected into index.html');
